import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';

const interR = Inter({
  subsets: ['latin'],
  weight: '400',
})


export const metadata: Metadata = {
  title: "BettaBeal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interR.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
