import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { Footer } from "./_components/Footer";
import { Header } from "./_components/Header";
import "./globals.css";
import Template from "./template";

const interR = Inter({
  subsets: ['latin'],
  weight: '400',
})


export const metadata: Metadata = {
  title: "BettaBeal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interR.className} antialiased`}
      >
        <Template>
          <Header />
          {children}
        </Template>
        <Footer />
      </body>
    </html>
  );
}
